from pathlib import Path

import pandas as pd


def load_tabular_predictions(file_path: Path) -> pd.DataFrame:
    """Load production predictions from the tabular model."""

    if not file_path.exists():
        raise FileNotFoundError(
            f"Tabular prediction file not found: {file_path}"
        )

    return pd.read_csv(file_path)


def load_vision_predictions(file_path: Path) -> pd.DataFrame:
    """Load predictions generated by the vision model."""

    if not file_path.exists():
        raise FileNotFoundError(
            f"Vision prediction file not found: {file_path}"
        )

    return pd.read_csv(file_path)


def create_fusion_summary(
    tabular_data: pd.DataFrame,
    vision_data: pd.DataFrame
) -> pd.DataFrame:
    """Create a combined quality intelligence summary."""

    tabular_defects = int(
        tabular_data["production_prediction"].sum()
    )

    tabular_total = len(tabular_data)

    vision_defects = int(
        vision_data["predicted_label"].sum()
    )

    vision_total = len(vision_data)

    summary = pd.DataFrame({
        "metric": [
            "Tabular Total Records",
            "Tabular Predicted Defects",
            "Tabular Defect Rate",
            "Vision Total Images",
            "Vision Predicted Defects",
            "Vision Defect Rate"
        ],
        "value": [
            tabular_total,
            tabular_defects,
            tabular_defects / tabular_total
            if tabular_total > 0 else 0,
            vision_total,
            vision_defects,
            vision_defects / vision_total
            if vision_total > 0 else 0
        ]
    })

    return summary


def save_fusion_results(
    summary: pd.DataFrame,
    output_path: Path
) -> None:
    """Save fusion results."""

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    summary.to_csv(
        output_path,
        index=False
    )


if __name__ == "__main__":

    project_root = (
        Path(__file__).resolve().parent.parent
    )

    tabular_predictions_path = (
        project_root
        / "outputs"
        / "reports"
        / "production_predictions.csv"
    )

    vision_predictions_path = (
        project_root
        / "outputs"
        / "reports"
        / "vision"
        / "vision_predictions.csv"
    )

    output_path = (
        project_root
        / "outputs"
        / "reports"
        / "data_fusion_summary.csv"
    )

    print("\n========== DATA FUSION ==========")

    print("\nLoading tabular predictions...")

    tabular_data = load_tabular_predictions(
        tabular_predictions_path
    )

    print(
        f"Tabular records: {len(tabular_data)}"
    )

    print("\nLoading vision predictions...")

    vision_data = load_vision_predictions(
        vision_predictions_path
    )

    print(
        f"Vision records: {len(vision_data)}"
    )

    print("\nCreating fusion summary...")

    summary = create_fusion_summary(
        tabular_data,
        vision_data
    )

    print("\n========== FUSION RESULTS ==========")
    print(summary.to_string(index=False))

    save_fusion_results(
        summary,
        output_path
    )

    print("\nFusion report saved to:")
    print(output_path)

    print("\n========== DATA FUSION COMPLETE ==========")